create table company (companyid integer generated by default as identity, company_name varchar(255), employees_number integer, primary key (companyid));
create table employee (id integer generated by default as identity, gender varchar(255), name varchar(255), primary key (id));
